// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBWVfJPexrJQIKr5r4qvpZzUzeVgapb-vs',
    appId: '1:1041212696439:web:5fbd49d1f87817d6726372',
    messagingSenderId: '1041212696439',
    projectId: 'promobilki-bc8ed',
    authDomain: 'promobilki-bc8ed.firebaseapp.com',
    storageBucket: 'promobilki-bc8ed.firebasestorage.app',
    measurementId: 'G-EZT6Y26YH6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAWLy-tiA2FqwRH12ZOTeOvrzoQo0JeH9U',
    appId: '1:1041212696439:android:731e6f281d88953f726372',
    messagingSenderId: '1041212696439',
    projectId: 'promobilki-bc8ed',
    storageBucket: 'promobilki-bc8ed.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIvEVlKsa0rlozQP86SzNmLFomJbpgRyA',
    appId: '1:1041212696439:ios:13a29e954c8029aa726372',
    messagingSenderId: '1041212696439',
    projectId: 'promobilki-bc8ed',
    storageBucket: 'promobilki-bc8ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIvEVlKsa0rlozQP86SzNmLFomJbpgRyA',
    appId: '1:1041212696439:ios:13a29e954c8029aa726372',
    messagingSenderId: '1041212696439',
    projectId: 'promobilki-bc8ed',
    storageBucket: 'promobilki-bc8ed.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBWVfJPexrJQIKr5r4qvpZzUzeVgapb-vs',
    appId: '1:1041212696439:web:04733b875bc5ed9e726372',
    messagingSenderId: '1041212696439',
    projectId: 'promobilki-bc8ed',
    authDomain: 'promobilki-bc8ed.firebaseapp.com',
    storageBucket: 'promobilki-bc8ed.firebasestorage.app',
    measurementId: 'G-72YE0FMVM5',
  );
}
